#!/usr/bin/env python3
"""Confidence-classifier registry: decide whether a decomp's own C
implementation of a guest function is trustworthy enough to wire into a
live game as a native func_override replacement -- the eligibility gate
the planned decomp-to-func_override generator needs (see
docs/ADDING_A_GAME.md, "Adding a confidence classifier", and postman.py /
docs/POSTMAN.md for the func_override side of that design).

GENERIC BY DESIGN, same contract as decomp_bridge.py / classifier_gap_finder.py
/ postman.py: a decomp's own confidence convention is looked up through
CONFIDENCE_CLASSIFIERS, keyed by the game's own [decomp] confidence_classifier
config value -- never hardcoded or assumed. A game whose config doesn't
declare one gets an UNKNOWN verdict, not a guess: this module fails closed on
missing eligibility information by design, because the thing it's gating is
native code that ends up running inside a live game.

Only one adapter exists so far: "source_quality", for Parasite Eve's own
tools/scripts/source_quality.py convention (semantic_c / asm_constrained /
text_data / original_asm per-file classification, described in that
project's docs/SOURCE_QUALITY.md). A different decomp bridged in later with
a different confidence convention needs its own adapter function registered
under its own name -- see "Adding a confidence classifier" in
docs/ADDING_A_GAME.md for the pattern, which mirrors decomp_bridge.py's own
SYMBOL_FORMATS registry.

WHAT "ELIGIBLE" ACTUALLY MEANS HERE, and why it's narrower than the decomp's
own progress-credit policy: Parasite Eve's own audit_report.py credits both
semantic_c AND original_asm as "done" for byte-match reporting purposes
(original_asm covers byte-matching BIOS-call trampolines that C cannot
express). This module's "eligible" is deliberately narrower: original_asm
means "this is raw assembly, not C", so there is no typed C for a
func_override adapter to call, no matter how well-verified the assembly is.
Confirmed against this project's own real data (tools/scripts/source_quality.py
run directly): Entity_ApplyCollisionResponse.c and five other real,
pin/barrier-bearing-but-ASM-free files all classify semantic_c as expected;
Sys_HleJumpA0.c and psyq/libc/strcmp.c (real BIOS-trampoline files) both
classify original_asm, confirming the two are genuinely distinguishable, not
a hypothetical distinction.

Byte-match verification (the second, stricter half of eligibility) reads
that decomp's own objdiff.json, if present -- generated by `make
objdiff-config`, a fast, pure-Python, non-compiling step in Parasite Eve's
own Makefile (see PR discussion; not something this module ever runs
itself, only reads if the user already has one). Each unit's
metadata.complete is set by that decomp's own tooling only when its
containing module's built binary SHA-1-matches retail AND its source_kind
is semantic_c/original_asm -- a real, project-computed byte-identity claim,
not something reconstructed here. No objdiff.json on disk means "can't
confirm a byte match", which this module reports as UNKNOWN, never as a
silent pass.

SHARED-LIBRARY .inc WRAPPERS (found running the real pipeline, see
findings/func_override-toolkit-pipeline-run-2026-09-16.md): a name like
`RoomLib_HandlerD` can exist as 100+ per-room `.c` files that are each a
two-line wrapper -- a comment plus `#include "../room_lib/RoomLib_HandlerD.inc"`
-- around ONE real, shared implementation. Naively, that's 100+ files with
the same name, an unresolvable ambiguity by plain filename matching.
`resolve_source_file` detects this specific shape (every candidate is a
wrapper with no function body of its own, all pointing at the exact same
`.inc` target) and resolves to the shared `.inc` directly instead of
refusing -- there is genuinely one confidence question here (is the shared
template semantic_c?), not one per room. Byte-match is a separate matter:
objdiff.json's units are keyed by each room's own compiled object, never by
the shared `.inc` itself (it's never independently compiled), so
`_classify_via_source_quality` looks up ONE representative room's wrapper
file for that half of the check and says so explicitly in the reported
reason -- this confirms the template compiles byte-identical in that one
room, not independently in every room that includes it. A name whose
per-room copies are genuinely DIFFERENT, independently-written
implementations that merely happen to share a PS1 overlay-reused address
(confirmed to also be real: `func_8018F71C` has three real, distinct
per-room bodies, not a wrapper) is correctly left ambiguous -- this
detection only fires when every candidate is provably a pure wrapper
pointing at the identical target.

Usage (standalone diagnostic; the real consumer is the planned generator):
  python bridge/confidence.py check-file \\
      --config games/parasite-eve/config.toml \\
      --source src/main/field/Entity_ApplyCollisionResponse.c

  python bridge/confidence.py check-address \\
      --config games/parasite-eve/config.toml --address 0x8001D170
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from decomp_bridge import GameConfig, load_config  # noqa: E402
from classifier_gap_finder import build_symbol_table, containing_function  # noqa: E402

ELIGIBLE = "eligible"
INELIGIBLE = "ineligible"
UNKNOWN = "unknown"


@dataclass
class ConfidenceResult:
    verdict: str                    # ELIGIBLE / INELIGIBLE / UNKNOWN
    reason: str
    source_kind: str | None = None  # source_quality's classify() result, if reached
    source_path: str | None = None  # decomp-relative path, if resolved
    shared_template_users: int | None = None  # set when source_path is a
        # room_lib/*.inc resolved from N per-room wrapper files sharing it --
        # None for an ordinary single-file resolution


# ----------------------------------------------------------------------------
# "source_quality" adapter -- Parasite Eve's own convention. The ONLY place
# in this module that knows anything PE-specific; see the module docstring.
# ----------------------------------------------------------------------------

def _load_source_quality(cfg: GameConfig):
    """Dynamically import THIS decomp checkout's own source_quality.py --
    not a copy bundled with this bridge -- so classification always reflects
    whatever version of that policy the decomp currently ships, the same way
    decomp_bridge.py always reads the decomp's own current symbol files
    rather than a cached copy."""
    path = cfg.decomp / "tools" / "scripts" / "source_quality.py"
    if not path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("_bridge_source_quality", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_objdiff_config(cfg: GameConfig) -> dict | None:
    path = cfg.decomp / "objdiff.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _find_unit_for_source(objdiff_config: dict, source_rel: str) -> dict | None:
    for unit in objdiff_config.get("units", []):
        if unit.get("metadata", {}).get("source_path") == source_rel:
            return unit
    return None


# ----------------------------------------------------------------------------
# Shared-library .inc wrapper detection -- see the module docstring's
# "SHARED-LIBRARY .inc WRAPPERS" section for why this exists and what it
# deliberately does NOT try to solve (per-room byte-match is still only
# checked for one representative room, never claimed universal).
# ----------------------------------------------------------------------------

_WRAPPER_INCLUDE_RE = re.compile(r'#\s*include\s*"([^"]+\.inc)"')


def _is_inc_wrapper(path: Path) -> Path | None:
    """A "thin wrapper" .c file: any #define/comment lines plus exactly one
    #include of a local .inc file, and NO function body of its own (no
    braces at all -- conservative on purpose: a stray brace just falls back
    to treating this as a real implementation, the safe failure direction).
    Returns the resolved absolute .inc path, or None if this file isn't
    shaped like a pure wrapper (e.g. func_8018F71C's real, independent
    per-room implementations, confirmed by direct reading -- see
    findings/func_override-toolkit-pipeline-run-2026-09-16.md)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    if "{" in text:
        return None
    matches = _WRAPPER_INCLUDE_RE.findall(text)
    if len(matches) != 1:
        return None
    target = (path.parent / matches[0]).resolve()
    return target if target.is_file() else None


def _resolve_via_shared_template(candidates: list[Path]) -> tuple[Path, Path] | None:
    """If EVERY candidate .c file is a thin wrapper around the exact same
    .inc target, return (representative_wrapper, shared_inc_path). None if
    any candidate isn't a pure wrapper, or they don't all point at the same
    target -- a real per-room difference, not just wrapper parameters."""
    targets: set[Path] = set()
    for c in candidates:
        t = _is_inc_wrapper(c)
        if t is None:
            return None
        targets.add(t)
    if len(targets) != 1:
        return None
    return candidates[0], next(iter(targets))


def _find_representative_wrapper(cfg: GameConfig, inc_abs_path: Path) -> Path | None:
    """Reverse of the above: given a shared .inc's own path, find one real
    per-room .c wrapper that includes it, for the objdiff.json byte-match
    lookup (which is keyed by each room's own compiled .c, never by the
    shared .inc itself -- it's never independently compiled). Deterministic
    (sorted) so re-running gives the same representative room every time."""
    for c_file in sorted(cfg.decomp.rglob("**/*.c")):
        if _is_inc_wrapper(c_file) == inc_abs_path:
            return c_file
    return None


def _classify_via_source_quality(cfg: GameConfig, source_rel: str) -> ConfidenceResult:
    sq = _load_source_quality(cfg)
    if sq is None:
        return ConfidenceResult(
            UNKNOWN,
            "tools/scripts/source_quality.py not found in this decomp "
            "checkout -- cannot classify", source_path=source_rel)

    abs_path = cfg.decomp / source_rel
    if not abs_path.is_file():
        return ConfidenceResult(
            UNKNOWN, f"{source_rel} does not exist in this decomp checkout",
            source_path=source_rel)

    kind = sq.classify(abs_path)
    # Deliberately narrower than this decomp's OWN progress-credit policy --
    # see the module docstring's "WHAT ELIGIBLE ACTUALLY MEANS" section.
    if kind != "semantic_c":
        return ConfidenceResult(
            INELIGIBLE,
            f"classified {kind!r}, not semantic_c -- no trustworthy C "
            "implementation for a func_override adapter to call",
            kind, source_rel)

    # A shared room_lib/*.inc template is never itself an independently
    # compiled unit -- objdiff.json only knows about the per-room wrapper
    # .c files that #include it. Resolve ONE representative room's wrapper
    # for the byte-match half of this check up front (regardless of whether
    # objdiff.json exists yet), and say so explicitly in every branch below:
    # this confirms the template compiles byte-identical in that one room,
    # not independently re-verified in every room that shares it.
    is_shared_template = abs_path.suffix == ".inc"
    lookup_rel = source_rel
    users = None
    if is_shared_template:
        resolved_inc = abs_path.resolve()
        users = sum(
            1 for c in cfg.decomp.rglob("**/*.c")
            if _is_inc_wrapper(c) == resolved_inc)
        rep = _find_representative_wrapper(cfg, resolved_inc)
        if rep is None:
            return ConfidenceResult(
                UNKNOWN,
                f"semantic_c (shared template {source_rel}, {users} "
                "per-room user(s)), but couldn't find any per-room wrapper "
                "file to check a byte-match against -- can't confirm a "
                "byte match", kind, source_rel, shared_template_users=users)
        lookup_rel = str(rep.relative_to(cfg.decomp)).replace("\\", "/")

    objdiff_config = _load_objdiff_config(cfg)
    if objdiff_config is None:
        detail = (f"semantic_c (shared template {source_rel}, {users} "
                   f"per-room user(s), representative room {lookup_rel})"
                   if is_shared_template else "semantic_c")
        return ConfidenceResult(
            UNKNOWN,
            f"{detail}, but this decomp's objdiff.json wasn't found -- run "
            "`make objdiff-config` there (after a build) to generate the "
            "byte-match evidence this needs before calling anything eligible",
            kind, source_rel, shared_template_users=users)

    unit = _find_unit_for_source(objdiff_config, lookup_rel)
    if unit is None:
        detail = (f"semantic_c (shared template {source_rel}, {users} "
                   f"per-room user(s)), but no objdiff.json unit references "
                   f"its representative wrapper {lookup_rel}"
                   if is_shared_template else
                   f"semantic_c, but no objdiff.json unit references {source_rel}")
        return ConfidenceResult(
            UNKNOWN, f"{detail} -- can't confirm a byte match",
            kind, source_rel, shared_template_users=users)

    if unit.get("metadata", {}).get("complete") is True:
        reason = (
            f"semantic_c, and objdiff.json marks representative room "
            f"{lookup_rel}'s containing module byte-verified against retail "
            f"-- confirmed for that one room, not independently re-checked "
            f"for all {users} rooms sharing this template"
            if is_shared_template else
            "semantic_c, and objdiff.json marks this unit's containing "
            "module byte-verified against retail")
        return ConfidenceResult(ELIGIBLE, reason, kind, source_rel,
                                 shared_template_users=users)

    detail = (f"semantic_c (shared template {source_rel}), but representative "
               f"room {lookup_rel}'s objdiff.json unit isn't marked complete"
               if is_shared_template else
               "semantic_c, but objdiff.json does not mark this unit complete")
    return ConfidenceResult(
        INELIGIBLE,
        f"{detail} -- its containing module hasn't been confirmed to build "
        "byte-identical to retail", kind, source_rel, shared_template_users=users)


CONFIDENCE_CLASSIFIERS = {
    "source_quality": _classify_via_source_quality,
}


# ----------------------------------------------------------------------------
# Public entry points
# ----------------------------------------------------------------------------

def classify_source_file(cfg: GameConfig, source_rel: str) -> ConfidenceResult:
    """Classify one decomp source file's func_override eligibility, using
    whatever confidence classifier this game's config.toml declares under
    [decomp] confidence_classifier. Fails closed (UNKNOWN) if this game
    hasn't declared one -- see docs/ADDING_A_GAME.md, "Adding a confidence
    classifier"."""
    name = cfg.confidence_classifier
    if not name:
        return ConfidenceResult(
            UNKNOWN,
            f"{cfg.game_id}'s config.toml has no [decomp] confidence_classifier "
            "declared -- refusing to assume which confidence convention "
            "applies (see docs/ADDING_A_GAME.md)", source_path=source_rel)
    fn = CONFIDENCE_CLASSIFIERS.get(name)
    if fn is None:
        return ConfidenceResult(
            UNKNOWN,
            f"unknown confidence_classifier {name!r} (known: "
            f"{sorted(CONFIDENCE_CLASSIFIERS)}) -- see docs/ADDING_A_GAME.md "
            "to add one", source_path=source_rel)
    return fn(cfg, source_rel)


_ADDR_SUFFIX_RE = re.compile(r"_([0-9A-Fa-f]{8})$")
_FUNC_DEF_RE_CACHE: dict[str, re.Pattern] = {}


def resolve_source_file(cfg: GameConfig, name: str, addr: int) -> str | None:
    """Best-effort address/name -> decomp-relative source file path.

    Same two-tier approach classifier_gap_finder.py's scan-pattern already
    validated: (1) exact filename match (`NAME.c`, or `NAME` already ending
    in the address suffix), which covers this project's overwhelmingly
    common one-function-per-file convention; (2) a content grep for a
    function DEFINITION matching this name, for the remaining files where
    the name doesn't appear in the filename. Heuristic, not a guarantee --
    same caveat classifier_gap_finder.py's containing_function() already
    carries: verify the result against the actual source before trusting it
    in isolation, especially for a tool that's about to gate native code
    generation on the answer.
    """
    exact = list(cfg.decomp.rglob(f"{name}.c"))
    if len(exact) == 1:
        return str(exact[0].relative_to(cfg.decomp)).replace("\\", "/")
    if len(exact) > 1:
        # Not necessarily unresolvable: if every candidate is a thin
        # room_lib/*.inc wrapper around the exact same shared template
        # (RoomLib_HandlerD-style, confirmed real -- see the module
        # docstring), there is genuinely one file to classify, not one per
        # room. A genuinely ambiguous name (independently-written per-room
        # copies, like func_8018F71C) falls through to None as before.
        via_template = _resolve_via_shared_template(exact)
        if via_template is not None:
            _, shared_inc = via_template
            return str(shared_inc.relative_to(cfg.decomp)).replace("\\", "/")
        return None  # ambiguous -- let the caller see UNKNOWN rather than guess

    addr_named = list(cfg.decomp.rglob(f"*_{addr:08X}.c"))
    if len(addr_named) == 1:
        return str(addr_named[0].relative_to(cfg.decomp)).replace("\\", "/")

    pattern = _FUNC_DEF_RE_CACHE.setdefault(
        name, re.compile(r"^[A-Za-z_][\w\s*]*\b" + re.escape(name) + r"\s*\(", re.MULTILINE))
    matches = []
    for c_file in cfg.decomp.rglob("**/*.c"):
        try:
            text = c_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if pattern.search(text):
            matches.append(c_file)
            if len(matches) > 1:
                break
    if len(matches) == 1:
        return str(matches[0].relative_to(cfg.decomp)).replace("\\", "/")
    return None


def classify_address(cfg: GameConfig, addr: int) -> ConfidenceResult:
    """Convenience wrapper: resolve addr -> containing function -> source
    file (via resolve_source_file's heuristic), then classify that file.
    Prefer classify_source_file directly when you already have a real file
    path (e.g. from classifier_gap_finder.py's scan-pattern output) --
    every extra resolution step here is one more heuristic that can be
    wrong."""
    table = build_symbol_table(cfg)
    name, offset = containing_function(table, addr)
    if name is None:
        return ConfidenceResult(
            UNKNOWN, f"no known symbol at or before 0x{addr:08X}")
    if offset != 0:
        return ConfidenceResult(
            UNKNOWN,
            f"0x{addr:08X} is {name}+0x{offset:X}, not {name}'s own start -- "
            "classify the actual containing function's address instead of "
            "an interior offset")
    source_rel = resolve_source_file(cfg, name, addr)
    if source_rel is None:
        return ConfidenceResult(
            UNKNOWN,
            f"found symbol {name} at 0x{addr:08X}, but couldn't resolve it "
            "to exactly one decomp source file -- resolve it yourself and "
            "use classify_source_file directly")
    return classify_source_file(cfg, source_rel)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p1 = sub.add_parser(
        "check-file",
        help="Classify one decomp source file's func_override eligibility.")
    p1.add_argument("--config", required=True)
    p1.add_argument("--source", required=True,
                     help="Decomp-relative source file path, e.g. "
                          "src/main/field/Entity_ApplyCollisionResponse.c")

    p2 = sub.add_parser(
        "check-address",
        help="Resolve a guest address to its containing decomp source file "
             "(best-effort) and classify that.")
    p2.add_argument("--config", required=True)
    p2.add_argument("--address", required=True, help="Hex guest address")

    args = ap.parse_args()
    cfg = load_config(Path(args.config))

    if args.cmd == "check-file":
        result = classify_source_file(cfg, args.source)
    else:
        addr = int(args.address, 16) if args.address.lower().startswith("0x") else int(args.address)
        result = classify_address(cfg, addr)

    print(f"verdict: {result.verdict}")
    print(f"reason:  {result.reason}")
    if result.source_kind:
        print(f"source_kind: {result.source_kind}")
    if result.source_path:
        print(f"source_path: {result.source_path}")
    if result.shared_template_users:
        print(f"shared_template_users: {result.shared_template_users} "
              "(other per-room addresses sharing this same template)")
    return 0 if result.verdict == ELIGIBLE else 1


if __name__ == "__main__":
    raise SystemExit(main())
