#!/usr/bin/env python3
"""Generic decomp -> psxrecomp symbol/seed bridge.

Feeds a fast-moving C decompilation's function symbols into a psxrecomp-based
static recompilation, as two build inputs psxrecomp itself defines the same
way for every title built on it:

  * <recomp_root>/symbols.toml   -- [[func]] pc / name / emit / status / note
  * <recomp_root>/<seeds path>   -- one 0xADDR per line (path read from the
                                     target's own game.toml [recompiler].seeds
                                     when present, so this engine never has to
                                     guess it)

Then it runs the recomp's own tools/sync_symbols.py -- part of psxrecomp's
"new_project_layout" scaffold, identical for every title -- to refresh
psx_symbols.h (the PSX_FN_* handles).

Everything GAME-SPECIFIC lives in a small TOML config under games/<name>/config.toml:
where the two checkouts are, what symbol-file format the decomp uses, the
valid RAM window for seeds, and name-collision handling. See
games/parasite-eve/config.toml for a worked example and docs/ADDING_A_GAME.md
for how to point this at a different decomp + psxrecomp pair.

Nothing here is committed into either upstream repo -- symbols.toml and the
seeds file are local, derived build inputs, regenerated by this tool.

Usage:
  python decomp_bridge.py --config games/parasite-eve/config.toml            # pull + regenerate
  python decomp_bridge.py --config games/parasite-eve/config.toml --no-pull  # regenerate only
  python decomp_bridge.py --config games/parasite-eve/config.toml --check    # CI: non-zero if stale

  # override the checkout locations in the config without editing it:
  python decomp_bridge.py --config games/parasite-eve/config.toml \\
      --decomp /path/to/parasite-eve-decomp --recomp /path/to/parasite-eve-recomp
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    print("error: need Python 3.11+", file=sys.stderr)
    raise SystemExit(2)

C_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")

# Default reserved-name set: libc / runtime identifiers a decomp's own
# function names commonly collide with. A game config can extend this
# (`[names] reserved_extra`) but shouldn't need to replace it.
DEFAULT_RESERVED = {
    "main", "exit", "abort", "atexit", "printf", "sprintf", "puts", "putchar",
    "malloc", "free", "calloc", "realloc",
    "memcpy", "memset", "memmove", "memcmp",
    "strcpy", "strncpy", "strcat", "strncat", "strcmp", "strncmp", "strlen",
    "strchr", "strrchr", "strstr", "strtok",
    "rand", "srand", "abs", "labs", "atoi", "atol", "qsort", "bsearch",
    "open", "close", "read", "write", "lseek", "getchar",
    "setjmp", "longjmp",
}


# --------------------------------------------------------------------------
# Symbol-file formats. `splat` is the only one implemented: the
# `NAME = 0xADDR; // type:func` convention used by khasinski/parasite-eve-decomp
# (shared with the splat/n64splat-family decomp tooling generally). Point a
# different decomp's config at a new value here and register a parser to
# support its format -- see docs/ADDING_A_GAME.md.
# --------------------------------------------------------------------------

_SPLAT_LINE = re.compile(
    r"^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;\s*(//.*)?$"
)


def _parse_splat(path: Path) -> list[tuple[str, int, bool]]:
    """Return (name, addr, is_func) for every `NAME = 0xADDR; // ...` line."""
    out = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = _SPLAT_LINE.match(line)
        if not m:
            continue
        name, addr_s, comment = m.group(1), m.group(2), (m.group(3) or "")
        addr = int(addr_s, 16) & 0xFFFFFFFF
        is_func = "type:func" in comment
        out.append((name, addr, is_func))
    return out


SYMBOL_FORMATS = {
    "splat": _parse_splat,
}


# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------

class GameConfig:
    def __init__(self, config_path: Path, data: dict):
        self.config_path = config_path
        base = config_path.parent

        self.game_id: str = data["game"]["id"]

        paths = data.get("paths", {})
        self.decomp = (base / paths["decomp"]).resolve()
        self.recomp = (base / paths["recomp"]).resolve()
        self.manual_toml = (base / paths["manual_toml"]).resolve() if paths.get("manual_toml") else None
        self.seeds_baseline = (base / paths["seeds_baseline"]).resolve() if paths.get("seeds_baseline") else None
        self.seeds_fallback = paths.get("seeds_fallback", "seeds/decomp_funcs.txt")

        decomp_cfg = data.get("decomp", {})
        fmt = decomp_cfg.get("format", "splat")
        if fmt not in SYMBOL_FORMATS:
            raise SystemExit(
                f"error: unknown [decomp].format {fmt!r} in {config_path} -- "
                f"known formats: {sorted(SYMBOL_FORMATS)} "
                f"(see docs/ADDING_A_GAME.md to add one)"
            )
        self.symbol_format = fmt
        self.main_symbol_files = [self.decomp / p for p in decomp_cfg["main_symbol_files"]]
        self.seed_symbol_globs = list(decomp_cfg.get("seed_symbol_globs", decomp_cfg["main_symbol_files"]))
        # Optional: which decomp-specific confidence convention bridge/confidence.py
        # should use for this game (see docs/ADDING_A_GAME.md, "Adding a
        # confidence classifier"). None means "not declared" -- confidence.py
        # fails closed on that, it never assumes a default.
        self.confidence_classifier: str | None = decomp_cfg.get("confidence_classifier")

        addrs = data.get("addresses", {})
        self.ram_lo = int(addrs.get("ram_lo", "0x80010000"), 0)
        self.ram_hi = int(addrs.get("ram_hi", "0x80200000"), 0)

        names = data.get("names", {})
        self.collision_prefix = names.get("collision_prefix", "G_")
        self.reserved = DEFAULT_RESERVED | set(names.get("reserved_extra", []))

    @property
    def out_symbols(self) -> Path:
        return self.recomp / "symbols.toml"

    @property
    def state_file(self) -> Path:
        return self.config_path.with_suffix(".state")

    def resolve_seed_files(self) -> list[Path]:
        files: list[Path] = []
        seen: set[Path] = set()
        for pattern in self.seed_symbol_globs:
            for p in sorted(self.decomp.glob(pattern)):
                if p not in seen:
                    seen.add(p)
                    files.append(p)
        return files

    def seeds_out_path(self) -> Path:
        """Where to write the seed list. Prefers the target's own
        game.toml [recompiler].seeds -- psxrecomp already knows where it
        wants seeds, so ask it instead of guessing."""
        game_toml = self.recomp / "game.toml"
        if game_toml.is_file():
            try:
                doc = tomllib.loads(game_toml.read_text(encoding="utf-8"))
                declared = doc.get("recompiler", {}).get("seeds")
                if declared:
                    return self.recomp / declared
            except Exception:
                pass
        return self.recomp / self.seeds_fallback


def load_config(path: Path) -> GameConfig:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    return GameConfig(path, data)


# --------------------------------------------------------------------------
# Bridge logic (game-agnostic)
# --------------------------------------------------------------------------

def log(msg: str) -> None:
    print(msg, flush=True)


def git_pull(repo: Path) -> str:
    """Pull a repo; return the new short SHA. Best-effort (offline = skip)."""
    git = os.environ.get("GIT", "git")
    try:
        before = subprocess.run(
            [git, "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        r = subprocess.run(
            [git, "-C", str(repo), "pull", "--ff-only", "--no-rebase"],
            capture_output=True, text=True,
        )
        after = subprocess.run(
            [git, "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        if r.returncode != 0:
            log(f"  ! git pull failed ({repo.name}), using local checkout:\n"
                f"    {r.stderr.strip().splitlines()[-1] if r.stderr.strip() else ''}")
        elif before != after:
            log(f"  decomp {before} -> {after}")
        else:
            log(f"  decomp unchanged at {after}")
        return after
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        log(f"  ! git unavailable ({e}); regenerating from local checkout")
        return "unknown"


def parse_symbol_file(cfg: GameConfig, path: Path) -> list[tuple[str, int, bool]]:
    return SYMBOL_FORMATS[cfg.symbol_format](path)


def load_manual(cfg: GameConfig) -> list[dict]:
    if not cfg.manual_toml or not cfg.manual_toml.is_file():
        return []
    data = tomllib.loads(cfg.manual_toml.read_text(encoding="utf-8"))
    funcs = []
    for raw in data.get("func", []):
        pc = raw["pc"] if isinstance(raw["pc"], int) else int(str(raw["pc"]), 0)
        funcs.append({
            "pc": pc & 0xFFFFFFFF,
            "name": str(raw["name"]),
            "emit": bool(raw.get("emit", False)),
            "status": str(raw.get("status", "guessed")),
            "note": str(raw.get("note", "")),
        })
    return funcs


def build_symbols_toml(cfg: GameConfig, manual: list[dict], decomp_sha: str) -> tuple[str, int]:
    entries: dict[int, dict] = {}
    taken_names: set[str] = set()

    # Manual entries win.
    for f in manual:
        entries[f["pc"]] = f
        taken_names.add(f["name"])

    skipped = 0
    for src in cfg.main_symbol_files:
        if not src.is_file():
            continue
        for name, addr, is_func in parse_symbol_file(cfg, src):
            if not is_func:
                continue
            if not C_IDENT.match(name):
                skipped += 1
                continue
            if addr in entries:            # manual override
                continue
            if name in cfg.reserved:
                name = f"{cfg.collision_prefix}{name}"
            if name in taken_names:        # name already used at another addr
                name = f"{name}_{addr:08X}"
            taken_names.add(name)
            entries[addr] = {
                "pc": addr, "name": name, "emit": False,
                "status": "confirmed",
                "note": f"decomp:{src.name}",
            }

    ordered = [entries[a] for a in sorted(entries)]
    lines = [
        f"# {cfg.game_id} - progressive symbol map",
        "# GENERATED by psxrecomp-decomp-bridge/bridge/decomp_bridge.py - do not hand-edit.",
        f"# Hand-authored entries: games/{cfg.game_id}/{cfg.manual_toml.name}" if cfg.manual_toml else "",
        f"# decomp source @ {decomp_sha}",
        f"# {len(ordered)} funcs ({len(manual)} manual)"
        + (f", {skipped} non-identifier names skipped" if skipped else ""),
        "",
    ]
    for f in ordered:
        lines.append("[[func]]")
        lines.append(f"pc = 0x{f['pc']:08X}")
        lines.append(f'name = "{f["name"]}"')
        lines.append(f"emit = {'true' if f['emit'] else 'false'}")
        lines.append(f'status = "{f["status"]}"')
        if f["note"]:
            lines.append(f'note = "{f["note"]}"')
        lines.append("")
    return "\n".join(l for l in lines if l is not None), len(ordered)


def build_seeds(cfg: GameConfig, decomp_sha: str) -> tuple[str, int, int]:
    baseline: list[str] = []
    if cfg.seeds_baseline and cfg.seeds_baseline.is_file():
        baseline = cfg.seeds_baseline.read_text(encoding="utf-8").splitlines()

    base_addrs: set[int] = set()
    for line in baseline:
        s = line.strip()
        if s.startswith("0x"):
            try:
                base_addrs.add(int(s, 16) & 0xFFFFFFFF)
            except ValueError:
                pass

    decomp_addrs: set[int] = set()
    for p in cfg.resolve_seed_files():
        for _name, addr, is_func in parse_symbol_file(cfg, p):
            if not is_func:
                continue
            if cfg.ram_lo <= addr < cfg.ram_hi:
                decomp_addrs.add(addr)

    all_addrs = sorted(base_addrs | decomp_addrs)
    new_from_decomp = len(decomp_addrs - base_addrs)

    baseline_note = f"games/{cfg.game_id}/{cfg.seeds_baseline.name}" if cfg.seeds_baseline else "(none configured)"
    header = [
        f"# Recompiler seed list for {cfg.game_id}",
        "# GENERATED by psxrecomp-decomp-bridge/bridge/decomp_bridge.py - do not hand-edit.",
        f"# = probe baseline ({baseline_note})",
        "#   + every decomp function address in range "
        f"0x{cfg.ram_lo:08X}..0x{cfg.ram_hi:08X}",
        f"# decomp source @ {decomp_sha}",
        f"# {len(all_addrs)} seeds "
        f"({len(base_addrs)} baseline, {new_from_decomp} added from decomp)",
        "",
    ]
    body = "\n".join(f"0x{a:08X}" for a in all_addrs)
    return "\n".join(header) + body + "\n", len(all_addrs), new_from_decomp


def run_recomp_sync_symbols(cfg: GameConfig) -> None:
    script = cfg.recomp / "tools" / "sync_symbols.py"
    if not script.is_file():
        log("  ! recomp tools/sync_symbols.py missing, skipping psx_symbols.h")
        return
    r = subprocess.run(
        [sys.executable, str(script), "--game", cfg.game_id],
        cwd=str(cfg.recomp), capture_output=True, text=True,
    )
    out = (r.stdout + r.stderr).strip()
    log(f"  {out}" if out else "  psx_symbols.h refreshed")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", required=True, type=Path, help="path to a games/<name>/config.toml")
    ap.add_argument("--decomp", type=Path, default=None,
                    help="override [paths].decomp from the config without editing it")
    ap.add_argument("--recomp", type=Path, default=None,
                    help="override [paths].recomp from the config without editing it")
    ap.add_argument("--no-pull", action="store_true", help="skip git pull")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if outputs would change (implies --no-pull)")
    ap.add_argument("--print-paths", action="store_true",
                    help="print resolved decomp=/recomp= paths and exit "
                         "(for build scripts that need the same paths this "
                         "config resolves to, instead of re-deriving them)")
    args = ap.parse_args()

    if not args.config.is_file():
        print(f"error: missing config {args.config}", file=sys.stderr)
        return 2
    cfg = load_config(args.config)
    if args.decomp:
        cfg.decomp = args.decomp.resolve()
    if args.recomp:
        cfg.recomp = args.recomp.resolve()

    if args.print_paths:
        print(f"decomp={cfg.decomp}")
        print(f"recomp={cfg.recomp}")
        return 0

    for p in (cfg.decomp, cfg.recomp):
        if not p.is_dir():
            print(f"error: missing {p}", file=sys.stderr)
            return 2
    if not any(p.is_file() for p in cfg.main_symbol_files):
        print(f"error: none of {cfg.main_symbol_files} exist", file=sys.stderr)
        return 2

    log(f"decomp_bridge: {cfg.game_id}")
    sha = "local"
    if args.check or args.no_pull:
        try:
            sha = subprocess.run(
                [os.environ.get("GIT", "git"), "-C", str(cfg.decomp),
                 "rev-parse", "--short", "HEAD"],
                capture_output=True, text=True, check=True).stdout.strip() or "local"
        except Exception:
            pass
    else:
        log("pulling decomp...")
        sha = git_pull(cfg.decomp) or "local"

    out_seeds = cfg.seeds_out_path()

    # First run: snapshot the recomp's own seed list as the baseline.
    if cfg.seeds_baseline and not cfg.seeds_baseline.is_file() and out_seeds.is_file():
        cfg.seeds_baseline.parent.mkdir(parents=True, exist_ok=True)
        cfg.seeds_baseline.write_text(
            out_seeds.read_text(encoding="utf-8"), encoding="utf-8")
        log(f"  snapshotted seed baseline -> {cfg.seeds_baseline.name}")

    sym_text, n_funcs = build_symbols_toml(cfg, load_manual(cfg), sha)
    seed_text, n_seeds, n_new = build_seeds(cfg, sha)

    if args.check:
        stale = False
        for path, text in ((cfg.out_symbols, sym_text), (out_seeds, seed_text)):
            cur = path.read_text(encoding="utf-8") if path.is_file() else None
            if cur != text:
                log(f"  STALE: {path}")
                stale = True
        return 1 if stale else 0

    cfg.out_symbols.write_text(sym_text, encoding="utf-8")
    out_seeds.parent.mkdir(parents=True, exist_ok=True)
    out_seeds.write_text(seed_text, encoding="utf-8")
    log(f"  symbols.toml : {n_funcs} funcs -> {cfg.out_symbols}")
    log(f"  seeds        : {n_seeds} addrs (+{n_new} from decomp) -> {out_seeds}")

    run_recomp_sync_symbols(cfg)

    cfg.state_file.write_text(f"{sha}\n{n_funcs}\n{n_seeds}\n", encoding="utf-8")
    log(f"done @ decomp {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
