#!/usr/bin/env python3
"""Generate a repeatable, on-demand invoker for one guest function address --
the "postman" tool from the func_override design discussion that grew out of
this project's own dirty-RAM/classifier-gap investigation
(findings/c4-wave5-fps-regression-2026-09-15.md and the design conversation
that followed it).

THE PROBLEM THIS SOLVES: verifying a candidate stuck-OBSERVED_PC_ONLY address
(the kind classifier_gap_finder.py finds) normally means reaching that exact
game state through live play -- which this project hit hard limits on this
same investigation (synthetic input could not reliably drive field movement
to reach several candidate RoomLib states). A postman sidesteps that: it
generates a native override, hung off ANY already-frequently-dispatched guest
address (the "trigger hook"), that polls a small scratch-RAM protocol and, on
request, calls the REAL target address on demand via psxrecomp's
func_override_guest_call -- so a human (or another tool) can invoke a
candidate function directly, with chosen argument values, without needing the
game to naturally reach that call site first.

*** REAL, UNMERGED DEPENDENCY -- READ BEFORE USING THE GENERATED CODE ***
This only works against RetroPortingToolKit/psxrecomp PR #174
("func_override tier"), branch feat/func-override-tier @ 6524ded0 as of
2026-09-16 -- an OPEN, UNMERGED, experimental branch, present in neither this
bridge's old known-good psxrecomp pin nor its current c4/wave5 pin. Using the
generated code means checking out that branch (or whatever it becomes once
reviewed/merged) in a LOCAL psxrecomp checkout -- a real, currently-external
dependency, not a guarantee this will compile against whatever pin your game
repo happens to use today.

The template below was written after actually reading func_override.h and
func_override.c from that exact commit (6524ded0) -- not just the PR's own
prose description -- and the generated .c file was test-compiled (syntax/
type-check only, -c against runtime/include, not linked into a real game)
against that checkout's real headers. Two non-obvious, easy-to-miss
requirements that verification surfaced, both called out again in the
generated file itself:
  1. func_override_install() MUST be called once at startup, AFTER every
     func_override_add() -- forgetting it leaves the dispatcher hook NULL,
     so every registered override (including this one) silently never
     fires. postman.py's own generated file cannot call this for you (it's
     a once-per-program step, not once-per-override); your init must.
  2. The override hook only consults on a genuine CALL (jal/jalr) to
     --trigger-hook, never on a tail transfer (j/jr) into it -- see
     func_override.h's "SCOPE" section. Pick a --trigger-hook address that
     is actually CALLED somewhere, or the poll handler never runs.
Still worth re-confirming against whatever commit you actually build
against, since this is a live, unmerged branch that can change.

GENERIC BY DESIGN, same contract as decomp_bridge.py / classifier_gap_finder.py:
everything game-specific is a CLI argument (target address, trigger hook
address, scratch RAM layout) -- this file contains no game-specific data, and
works for any psxrecomp-based title once that title's own func_override
branch is available, not just Parasite Eve's.

Usage:
  python bridge/postman.py generate \\
      --target 0x80190B70 --arg-types u32,u32,ptr,u32 \\
      --trigger-hook 0x80046264 \\
      --trigger-addr 0x800A1000 --args-addr 0x800A1004 --result-addr 0x800A1014 \\
      --id postman_roomlib_test \\
      --out generated/postman_roomlib_test.c

This only WRITES a .c file -- it never touches a live game, a recompiler, or
any build files. Wiring the generated file into your build and calling its
`<id>_register()` from your game's own override/mod init routine is a manual,
separate step (see the usage comment psxrecomp's generator prints at the top
of the generated file).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ARG_TYPES = {
    "u32": ("uint32_t", "unsigned 32-bit value"),
    "s32": ("int32_t", "signed 32-bit value"),
    "ptr": ("uint32_t", "guest pointer (32-bit guest address, not a host pointer)"),
}
RET_TYPES = {**ARG_TYPES, "void": ("void", "no return value read")}

MAX_REG_ARGS = 4  # $a0-$a3 only -- stack-passed args (5th+) are NOT implemented.

HEADER_COMMENT = """\
/* GENERATED by psxrecomp-decomp-bridge/bridge/postman.py -- do not hand-edit.
 * Regenerate with the same command instead (see the invocation recorded
 * below) if you need to change the target, args, or scratch addresses.
 *
 * WHAT THIS IS: a "postman" -- an on-demand invoker for guest function
 * {target_hex}, piggybacked on the already-frequently-dispatched guest
 * CODE address {trigger_hex} via psxrecomp's func_override tier (see
 * docs/POSTMAN.md in psxrecomp-decomp-bridge for the full design and the
 * *** REAL DEPENDENCY WARNING *** about PR #174 being open/unmerged as of
 * generation time -- read it before wiring this in).
 *
 * PROTOCOL (poll-based, scratch guest RAM DATA you must reserve and never
 * let the game itself read or write -- pick addresses outside any range the
 * game or its overlays actually use; these are DATA addresses, distinct
 * from {trigger_hex} above, which is a CODE address being overridden):
 *   {flag_hex}  (1 word)  writer sets to 1 to REQUEST a call; this
 *                             handler sets it to 2 when the result is ready,
 *                             back to 0 once you've read it (writer's job).
 *   {args_hex}  ({argc} word{plural})  arg0..arg{argc_m1} in order, read
 *                             ONLY at the moment a request (flag==1) is
 *                             seen -- write these BEFORE setting flag=1.
 *   {result_hex}  (1 word)  the call's $v0 on return; valid once flag==2.
 *
 * This handler ALWAYS returns 0 (declines) so {trigger_hex}'s own original
 * behavior is completely unaffected -- it only piggybacks a poll on it, it
 * never blocks or replaces the function actually being overridden there.
 *
 * *** DO NOT FORGET (silent-failure risk, not a compile error) ***
 * func_override_install() must be called ONCE at program startup, AFTER
 * every func_override_add() call including this one's {id}_register() --
 * omitting it leaves the dispatcher hook NULL and NOTHING registered ever
 * fires, with no error, no log, nothing. This file cannot call it for you
 * (it's a once-per-program step, not once-per-override).
 *
 * {trigger_hex} must be reached via a genuine CALL (jal/jalr) somewhere in
 * this game's code -- a tail transfer (j/jr) into it does NOT consult the
 * override hook at all (func_override.h's own "SCOPE" section). If you pick
 * a trigger-hook that's only ever tail-jumped to, this handler never runs.
 *
 * CONFIRMED against RetroPortingToolKit/psxrecomp @ 6524ded0 (PR #174's
 * feat/func-override-tier, read directly -- func_override.h/.c, cpu_state.h,
 * memory.c -- not just the PR's own prose description) and test-compiled
 * (syntax/type-check, -c against runtime/include) at generation time:
 *   - func_override_guest_call(cpu, target, site_ra): args go in
 *     cpu->gpr[4..7] before the call (o32 convention, CPUState.gpr[32]
 *     confirmed in runtime/include/cpu_state.h), result comes back in
 *     cpu->gpr[2]. site_ra is a STOP-PC sentinel for the internal dispatch
 *     loop (func_override.c: psx_dispatch_call runs target "to completion,
 *     pc == site_ra") -- it does not need to be a real pre-existing call
 *     site for the mechanism to work, though func_override.h recommends an
 *     authentic return address for fntrace/crash-forensics readability.
 *     This generator passes {trigger_hex} itself. EDGE CASE worth knowing:
 *     if {trigger_hex} ever appears as an internal branch target inside
 *     {target_hex}'s own instruction stream, the dispatch loop could stop
 *     early -- vanishingly unlikely for two unrelated functions, but a real
 *     failure mode if target and trigger-hook happen to sit close together.
 *   - Guest memory access inside an override goes through the CPUState's
 *     own read_word/write_word function-pointer members (cpu_state.h:
 *     "wired at init to psx_read/psx_write"), not a free function you must
 *     declare yourself -- this template uses cpu->read_word/cpu->write_word.
 *   - credit=FO_CREDIT_SELF at registration is inert for this specific
 *     pattern: func_override.c only charges the declared credit when an
 *     override HANDLES a call (returns nonzero); this handler always
 *     declines, so its own credit is never consulted. The guest call this
 *     handler makes to {target_hex} self-charges normally through the
 *     ordinary dispatch backends regardless.
 *   - Stack-passed arguments (5th+) are UNIMPLEMENTED -- this generator
 *     refuses more than {max_args} arg-types for exactly that reason.
 *
 * Still worth re-confirming against whatever commit you actually build
 * against -- this is a live, unmerged branch that can change.
 */

"""

C_TEMPLATE = """\
#include <stdint.h>
#include "cpu_state.h"      /* full CPUState definition -- func_override.h only
                                forward-declares it, but this handler dereferences
                                cpu->gpr[]/cpu->read_word/cpu->write_word below,
                                which needs the real struct layout in scope */
#include "func_override.h"  /* from RetroPortingToolKit/psxrecomp PR #174 --
                                path may need adjusting to match your checkout */

static int {id}_handler(CPUState* cpu) {{
    if (cpu->read_word({flag_hex}u) != 1u) {{
        return 0;  /* no request pending -- decline, let the original run */
    }}

{arg_reads}
    func_override_guest_call(cpu, {target_hex}u, {trigger_hex}u);

{ret_write}
    cpu->write_word({flag_hex}u, 2u);  /* mark result ready */
    return 0;  /* never blocks the piggybacked hook's own original behavior */
}}

void {id}_register(void) {{
    /* credit=FO_CREDIT_SELF: inert here since this handler always declines
       (see the header comment above) -- kept for an honest registration
       rather than claiming a fixed replaced-code cost that doesn't apply. */
    func_override_add("{id}", {trigger_hex}u, {id}_handler, FO_CREDIT_SELF);
    /* REMINDER: func_override_install() must ALSO be called once, after
       every override (including this one) is registered -- NOT from here.
       See this file's header comment. */
}}
"""


def emit_arg_reads(arg_types: list[str], args_hex: str) -> str:
    lines = []
    for i, t in enumerate(arg_types):
        c_type, _ = ARG_TYPES[t]
        addr_expr = f"({args_hex}u + {i * 4}u)"
        lines.append(
            f"    cpu->gpr[4 + {i}] = ({c_type})cpu->read_word({addr_expr});"
            f"  /* arg{i}: {t} */"
        )
    return "\n".join(lines)


def emit_ret_write(ret_type: str, result_hex: str) -> str:
    if ret_type == "void":
        return "    /* no return value declared -- result scratch word left untouched */"
    c_type, _ = ARG_TYPES.get(ret_type, RET_TYPES[ret_type])
    return (
        f"    cpu->write_word({result_hex}u, ({c_type})cpu->gpr[2]);"
        f"  /* $v0 -> result: {ret_type} */"
    )


def cmd_generate(args: argparse.Namespace) -> int:
    arg_types = [t.strip() for t in args.arg_types.split(",")] if args.arg_types else []
    for t in arg_types:
        if t not in ARG_TYPES:
            print(f"error: unknown --arg-types entry {t!r} "
                  f"(known: {sorted(ARG_TYPES)})", file=sys.stderr)
            return 2
    if len(arg_types) > MAX_REG_ARGS:
        print(f"error: {len(arg_types)} args requested, but only "
              f"{MAX_REG_ARGS} register-passed args ($a0-$a3) are "
              "implemented -- stack-passed args are NOT supported by this "
              "generator yet.", file=sys.stderr)
        return 2
    if args.ret_type not in RET_TYPES:
        print(f"error: unknown --ret-type {args.ret_type!r} "
              f"(known: {sorted(RET_TYPES)})", file=sys.stderr)
        return 2

    def parse_addr(s: str) -> int:
        return int(s, 16) if s.lower().startswith("0x") else int(s)

    target = parse_addr(args.target)
    trigger = parse_addr(args.trigger_hook)
    flag_addr = parse_addr(args.trigger_addr)
    args_addr = parse_addr(args.args_addr)
    result_addr = parse_addr(args.result_addr)

    if len({trigger, flag_addr, args_addr, result_addr}) != 4:
        print("error: --trigger-hook (a CODE address), --trigger-addr, "
              "--args-addr, and --result-addr (all scratch DATA addresses) "
              "must all be distinct -- got an overlap, which would corrupt "
              "either the override registration or the protocol words.",
              file=sys.stderr)
        return 2

    target_hex = f"0x{target:08X}"
    trigger_hex = f"0x{trigger:08X}"
    flag_hex = f"0x{flag_addr:08X}"
    args_hex = f"0x{args_addr:08X}"
    result_hex = f"0x{result_addr:08X}"

    header = HEADER_COMMENT.format(
        target_hex=target_hex, trigger_hex=trigger_hex, flag_hex=flag_hex,
        args_hex=args_hex, result_hex=result_hex, argc=len(arg_types) or 0,
        plural="" if len(arg_types) == 1 else "s",
        argc_m1=max(len(arg_types) - 1, 0), max_args=MAX_REG_ARGS, id=args.id,
    )
    body = C_TEMPLATE.format(
        id=args.id,
        trigger_hex=trigger_hex,
        flag_hex=flag_hex,
        target_hex=target_hex,
        arg_reads=emit_arg_reads(arg_types, args_hex) if arg_types else
                   "    /* no arguments declared */",
        ret_write=emit_ret_write(args.ret_type, result_hex),
    )

    invocation = "  ".join(
        f"--{k.replace('_', '-')} {v}" for k, v in vars(args).items()
        if k not in ("func", "cmd")
    )
    full = header + f"/* Generated with: postman.py generate {invocation} */\n\n" + body

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(full, encoding="utf-8")
    print(f"wrote {out_path} ({len(arg_types)} arg(s), ret={args.ret_type})")
    print(
        "\nNext steps (all manual, none of this touches your build):\n"
        "  1. Pull RetroPortingToolKit/psxrecomp PR #174's branch "
        "(feat/func-override-tier) into a psxrecomp checkout your game can "
        "build against -- it is NOT in your current pin. Re-confirm the "
        "generated file's header comment against whatever commit you "
        "actually check out; it's a live, unmerged branch that can change.\n"
        f"  2. Add {out_path.name} to your build and call "
        f"{args.id}_register() from your game's own override/mod init.\n"
        "  3. *** Also call func_override_install() once, AFTER every "
        "override (including this one) is registered *** -- this is a "
        "silent-failure trap, not a compile error: skip it and nothing "
        "registered ever fires, with no diagnostic at all.\n"
        f"  4. Confirm {trigger_hex} is reached via a genuine CALL "
        "(jal/jalr) somewhere in this game -- a tail-jump-only target never "
        "consults the override hook, so the poll handler would never run.\n"
        f"  5. To invoke: write arg words to {args_hex}, then write 1 to "
        f"{flag_hex}; poll it for 2; read the result from {result_hex}."
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser(
        "generate",
        help="Generate a func_override-based on-demand invoker .c file for "
             "one guest function address.")
    p.add_argument("--target", required=True,
                    help="Guest address of the function to invoke on demand "
                         "(hex, e.g. 0x80190B70)")
    p.add_argument("--trigger-hook", required=True,
                    help="Guest address of an ALREADY frequently-dispatched "
                         "function to piggyback the poll on (e.g. a per-frame "
                         "tick or main-loop function this game's own "
                         "dirty-RAM/capture data already shows executing "
                         "constantly). Must be reached via a genuine CALL "
                         "(jal/jalr) somewhere -- a tail-jump-only (j/jr) "
                         "target never consults the override hook at all, so "
                         "the poll handler would never run. This override "
                         "always declines, so the hooked function's own "
                         "behavior is unaffected.")
    p.add_argument("--trigger-addr", required=True,
                    help="Scratch guest RAM word (hex) used as the "
                         "request/ready flag. Must be an address the game "
                         "itself never reads or writes -- pick unused RAM, "
                         "not a guess.")
    p.add_argument("--args-addr", required=True,
                    help="Scratch guest RAM (hex) where arg0..argN-1 are "
                         "read from, one word each, at request time.")
    p.add_argument("--result-addr", required=True,
                    help="Scratch guest RAM word (hex) the call's return "
                         "value ($v0) is written to.")
    p.add_argument("--arg-types", default="",
                    help="Comma-separated arg types in order, e.g. "
                         f"u32,ptr,u32 (max {MAX_REG_ARGS}; known types: "
                         f"{sorted(ARG_TYPES)}). Empty for a no-argument call.")
    p.add_argument("--ret-type", default="u32",
                    help=f"Return type (known: {sorted(RET_TYPES)}, "
                         "default u32; use 'void' if the target doesn't "
                         "return a meaningful value)")
    p.add_argument("--id", required=True,
                    help="C identifier prefix for the generated handler/"
                         "register function names -- must be unique across "
                         "every postman override registered in your build.")
    p.add_argument("--out", required=True, help="Output .c file path")
    p.set_defaults(func=cmd_generate)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
