#!/usr/bin/env python3
"""Generate a repeatable, on-demand invoker for one guest function address --
the "postman" tool from the func_override design discussion that grew out of
this project's own dirty-RAM/classifier-gap investigation
(findings/c4-wave5-fps-regression-2026-09-15.md and the design conversation
that followed it).

THE PROBLEM THIS SOLVES: verifying a candidate stuck-OBSERVED_PC_ONLY address
(the kind classifier_gap_finder.py finds) normally means reaching that exact
game state through live play -- which this project hit hard limits on this
same investigation (synthetic input could not reliably drive field movement
to reach several candidate RoomLib states). A postman sidesteps that: it
generates a native override, hung off ANY already-frequently-dispatched guest
address (the "trigger hook"), that polls a small scratch-RAM protocol and, on
request, calls the REAL target address on demand via psxrecomp's
func_override_guest_call -- so a human (or another tool) can invoke a
candidate function directly, with chosen argument values, without needing the
game to naturally reach that call site first.

*** REAL, UNMERGED DEPENDENCY -- READ BEFORE USING THE GENERATED CODE ***
This only works against RetroPortingToolKit/psxrecomp PR #174
("func_override tier"), branch feat/func-override-tier @ 6524ded0 as of
2026-09-16 -- an OPEN, UNMERGED, experimental branch, present in neither this
bridge's old known-good psxrecomp pin nor its current c4/wave5 pin. Using the
generated code means checking out that branch (or whatever it becomes once
reviewed/merged) in a LOCAL psxrecomp checkout -- a real, currently-external
dependency, not a guarantee this will compile against whatever pin your game
repo happens to use today. Verify func_override.h's actual signatures against
whatever commit you check out before trusting the generated call site
verbatim; some details below (see "UNVERIFIED" markers in the generated
output) are inferred from the PR's own description, not read from the header
directly, because the header wasn't fetchable as raw source at generation
time.

GENERIC BY DESIGN, same contract as decomp_bridge.py / classifier_gap_finder.py:
everything game-specific is a CLI argument (target address, trigger hook
address, scratch RAM layout) -- this file contains no game-specific data, and
works for any psxrecomp-based title once that title's own func_override
branch is available, not just Parasite Eve's.

Usage:
  python bridge/postman.py generate \\
      --target 0x80190B70 --arg-types u32,u32,ptr,u32 \\
      --trigger-hook 0x80046264 \\
      --trigger-addr 0x800A1000 --args-addr 0x800A1004 --result-addr 0x800A1014 \\
      --id postman_roomlib_test \\
      --out generated/postman_roomlib_test.c

This only WRITES a .c file -- it never touches a live game, a recompiler, or
any build files. Wiring the generated file into your build and calling its
`<id>_register()` from your game's own override/mod init routine is a manual,
separate step (see the usage comment psxrecomp's generator prints at the top
of the generated file).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ARG_TYPES = {
    "u32": ("uint32_t", "unsigned 32-bit value"),
    "s32": ("int32_t", "signed 32-bit value"),
    "ptr": ("uint32_t", "guest pointer (32-bit guest address, not a host pointer)"),
}
RET_TYPES = {**ARG_TYPES, "void": ("void", "no return value read")}

MAX_REG_ARGS = 4  # $a0-$a3 only -- stack-passed args (5th+) are NOT implemented.

HEADER_COMMENT = """\
/* GENERATED by psxrecomp-decomp-bridge/bridge/postman.py -- do not hand-edit.
 * Regenerate with the same command instead (see the invocation recorded
 * below) if you need to change the target, args, or scratch addresses.
 *
 * WHAT THIS IS: a "postman" -- an on-demand invoker for guest function
 * {target_hex}, piggybacked on the already-frequently-dispatched guest
 * CODE address {trigger_hex} via psxrecomp's func_override tier (see
 * docs/POSTMAN.md in psxrecomp-decomp-bridge for the full design and the
 * *** REAL DEPENDENCY WARNING *** about PR #174 being open/unmerged as of
 * generation time -- read it before wiring this in).
 *
 * PROTOCOL (poll-based, scratch guest RAM DATA you must reserve and never
 * let the game itself read or write -- pick addresses outside any range the
 * game or its overlays actually use; these are DATA addresses, distinct
 * from {trigger_hex} above, which is a CODE address being overridden):
 *   {flag_hex}  (1 word)  writer sets to 1 to REQUEST a call; this
 *                             handler sets it to 2 when the result is ready,
 *                             back to 0 once you've read it (writer's job).
 *   {args_hex}  ({argc} word{plural})  arg0..arg{argc_m1} in order, read
 *                             ONLY at the moment a request (flag==1) is
 *                             seen -- write these BEFORE setting flag=1.
 *   {result_hex}  (1 word)  the call's $v0 on return; valid once flag==2.
 *
 * This handler ALWAYS returns 0 (declines) so {trigger_hex}'s own original
 * behavior is completely unaffected -- it only piggybacks a poll on it, it
 * never blocks or replaces the function actually being overridden there.
 *
 * UNVERIFIED (confirm against your actual func_override.h before trusting):
 *   - func_override_guest_call's exact `site_ra` semantics. This generator
 *     passes {trigger_hex} (the piggyback hook's own address) as site_ra,
 *     assuming "resume at the hook's own dispatch site" is a valid/authentic
 *     return address -- the PR description says "authentic return addresses"
 *     but the exact contract (does it need to be a real call site already on
 *     the dispatch chokepoint, or is a synthetic pseudo-return-address
 *     acceptable?) was not confirmed against the real header source, only
 *     against the PR's own prose description, at generation time.
 *   - Whether func_override_guest_call expects gpr[4..7] pre-loaded by the
 *     caller (assumed here, matching o32 convention and the framework's own
 *     CPUState.gpr[32] layout confirmed in recompiler/include/code_generator.h)
 *     or takes arguments some other way.
 *   - Stack-passed arguments (5th+) are UNIMPLEMENTED -- this generator
 *     refuses more than {max_args} arg-types for exactly that reason.
 */

"""

C_TEMPLATE = """\
#include <stdint.h>
#include "func_override.h"  /* from RetroPortingToolKit/psxrecomp PR #174 --
                                path may need adjusting to match your checkout */

struct CPUState;  /* full definition not needed here; func_override.h's own
                      declarations are what actually get used below */

static int {id}_handler(struct CPUState* cpu) {{
    extern uint32_t psx_read_u32(uint32_t addr);   /* UNVERIFIED name -- use
        whatever guest-memory-read helper your psxrecomp pin actually exposes;
        this project's own runtime almost certainly already has one under a
        different name (see runtime/include/*.h for the real symbol). */
    extern void     psx_write_u32(uint32_t addr, uint32_t value);  /* ditto */

    if (psx_read_u32({flag_hex}u) != 1u) {{
        return 0;  /* no request pending -- decline, let the original run */
    }}

{arg_reads}
    func_override_guest_call(cpu, {target_hex}u, {trigger_hex}u);

{ret_write}
    psx_write_u32({flag_hex}u, 2u);  /* mark result ready */
    return 0;  /* never blocks the piggybacked hook's own original behavior */
}}

void {id}_register(void) {{
    /* credit=FO_CREDIT_SELF: this override manages its own timing (a poll +
       occasional guest call), not a fixed per-call cycle cost. Confirm this
       is the right choice for your case -- see func_override.h's own
       comments on FO_CREDIT_SELF vs. a fixed integer credit. */
    func_override_add("{id}", {trigger_hex}u, {id}_handler, FO_CREDIT_SELF);
}}
"""


def emit_arg_reads(arg_types: list[str], args_hex: str) -> str:
    lines = []
    for i, t in enumerate(arg_types):
        c_type, _ = ARG_TYPES[t]
        addr_expr = f"({args_hex}u + {i * 4}u)"
        lines.append(
            f"    cpu->gpr[4 + {i}] = ({c_type})psx_read_u32({addr_expr});"
            f"  /* arg{i}: {t} */"
        )
    return "\n".join(lines)


def emit_ret_write(ret_type: str, result_hex: str) -> str:
    if ret_type == "void":
        return "    /* no return value declared -- result scratch word left untouched */"
    c_type, _ = ARG_TYPES.get(ret_type, RET_TYPES[ret_type])
    return (
        f"    psx_write_u32({result_hex}u, ({c_type})cpu->gpr[2]);"
        f"  /* $v0 -> result: {ret_type} */"
    )


def cmd_generate(args: argparse.Namespace) -> int:
    arg_types = [t.strip() for t in args.arg_types.split(",")] if args.arg_types else []
    for t in arg_types:
        if t not in ARG_TYPES:
            print(f"error: unknown --arg-types entry {t!r} "
                  f"(known: {sorted(ARG_TYPES)})", file=sys.stderr)
            return 2
    if len(arg_types) > MAX_REG_ARGS:
        print(f"error: {len(arg_types)} args requested, but only "
              f"{MAX_REG_ARGS} register-passed args ($a0-$a3) are "
              "implemented -- stack-passed args are NOT supported by this "
              "generator yet.", file=sys.stderr)
        return 2
    if args.ret_type not in RET_TYPES:
        print(f"error: unknown --ret-type {args.ret_type!r} "
              f"(known: {sorted(RET_TYPES)})", file=sys.stderr)
        return 2

    def parse_addr(s: str) -> int:
        return int(s, 16) if s.lower().startswith("0x") else int(s)

    target = parse_addr(args.target)
    trigger = parse_addr(args.trigger_hook)
    flag_addr = parse_addr(args.trigger_addr)
    args_addr = parse_addr(args.args_addr)
    result_addr = parse_addr(args.result_addr)

    if len({trigger, flag_addr, args_addr, result_addr}) != 4:
        print("error: --trigger-hook (a CODE address), --trigger-addr, "
              "--args-addr, and --result-addr (all scratch DATA addresses) "
              "must all be distinct -- got an overlap, which would corrupt "
              "either the override registration or the protocol words.",
              file=sys.stderr)
        return 2

    target_hex = f"0x{target:08X}"
    trigger_hex = f"0x{trigger:08X}"
    flag_hex = f"0x{flag_addr:08X}"
    args_hex = f"0x{args_addr:08X}"
    result_hex = f"0x{result_addr:08X}"

    header = HEADER_COMMENT.format(
        target_hex=target_hex, trigger_hex=trigger_hex, flag_hex=flag_hex,
        args_hex=args_hex, result_hex=result_hex, argc=len(arg_types) or 0,
        plural="" if len(arg_types) == 1 else "s",
        argc_m1=max(len(arg_types) - 1, 0), max_args=MAX_REG_ARGS,
    )
    body = C_TEMPLATE.format(
        id=args.id,
        trigger_hex=trigger_hex,
        flag_hex=flag_hex,
        target_hex=target_hex,
        arg_reads=emit_arg_reads(arg_types, args_hex) if arg_types else
                   "    /* no arguments declared */",
        ret_write=emit_ret_write(args.ret_type, result_hex),
    )

    invocation = "  ".join(
        f"--{k.replace('_', '-')} {v}" for k, v in vars(args).items()
        if k not in ("func", "cmd")
    )
    full = header + f"/* Generated with: postman.py generate {invocation} */\n\n" + body

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(full, encoding="utf-8")
    print(f"wrote {out_path} ({len(arg_types)} arg(s), ret={args.ret_type})")
    print(
        "\nNext steps (all manual, none of this touches your build):\n"
        "  1. Pull RetroPortingToolKit/psxrecomp PR #174's branch "
        "(feat/func-override-tier) into a psxrecomp checkout your game can "
        "build against -- it is NOT in your current pin.\n"
        "  2. Read the real func_override.h from that checkout and fix the "
        "UNVERIFIED items noted in the generated file's header comment "
        "(guest-memory read/write helper names, site_ra semantics).\n"
        f"  3. Add {out_path.name} to your build and call "
        f"{args.id}_register() from your game's own override/mod init.\n"
        f"  4. To invoke: write arg words to {args_hex}, then write 1 to "
        f"{flag_hex}; poll it for 2; read the result from {result_hex}."
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser(
        "generate",
        help="Generate a func_override-based on-demand invoker .c file for "
             "one guest function address.")
    p.add_argument("--target", required=True,
                    help="Guest address of the function to invoke on demand "
                         "(hex, e.g. 0x80190B70)")
    p.add_argument("--trigger-hook", required=True,
                    help="Guest address of an ALREADY frequently-dispatched "
                         "function to piggyback the poll on (e.g. a per-frame "
                         "tick or main-loop function this game's own "
                         "dirty-RAM/capture data already shows executing "
                         "constantly). This override always declines, so the "
                         "hooked function's own behavior is unaffected.")
    p.add_argument("--trigger-addr", required=True,
                    help="Scratch guest RAM word (hex) used as the "
                         "request/ready flag. Must be an address the game "
                         "itself never reads or writes -- pick unused RAM, "
                         "not a guess.")
    p.add_argument("--args-addr", required=True,
                    help="Scratch guest RAM (hex) where arg0..argN-1 are "
                         "read from, one word each, at request time.")
    p.add_argument("--result-addr", required=True,
                    help="Scratch guest RAM word (hex) the call's return "
                         "value ($v0) is written to.")
    p.add_argument("--arg-types", default="",
                    help="Comma-separated arg types in order, e.g. "
                         f"u32,ptr,u32 (max {MAX_REG_ARGS}; known types: "
                         f"{sorted(ARG_TYPES)}). Empty for a no-argument call.")
    p.add_argument("--ret-type", default="u32",
                    help=f"Return type (known: {sorted(RET_TYPES)}, "
                         "default u32; use 'void' if the target doesn't "
                         "return a meaningful value)")
    p.add_argument("--id", required=True,
                    help="C identifier prefix for the generated handler/"
                         "register function names -- must be unique across "
                         "every postman override registered in your build.")
    p.add_argument("--out", required=True, help="Output .c file path")
    p.set_defaults(func=cmd_generate)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
